name: data-lunch
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - click=8.0.4
  - ipykernel=6.15.2
  - ipywidgets=7.6.5
  - openpyxl=3.0.10
  - pandas=1.4.4
  - tqdm=4.64.1
  - panel=0.14.0
  - sqlalchemy=1.4.39
  - hydra-core=1.1.1
  - google-cloud-storage=1.43.0
